import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import StyledComponentsRegistry from '@/lib/registy'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portopolio-Dimas-Febriyanto',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     <StyledComponentsRegistry> <body className={inter.className}>{children}</body></StyledComponentsRegistry>
    </html>
  )
}
